### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by c0d3rman** [c0d3rman/p5-libraries#1]
- [ ] Add wrapper tool for handling many hitboxes all colliding
- [ ] Make everything lazy-compute
- [ ] Add caching
- [ ] Enable better hitbox reuse with fast translation/rotation
- [ ] Optimization for ellipse-ellipse collisions where both happen to be circles (common enough case to justify)

## LOGISTICS
- [ ] Add parameter verification and 3d warning
- [ ] Deal with p5 global mode and instance mode
- [ ] Add support for custom canvas object - requires nanigans with like ellipseMode and pixelDensity and stuff

## TESTING
- [ ] Test mode args
- [ ] Do a full collision test (alongside a simple bounding-circle test for each shape)
- [ ] Test degenerate cases (0-size shapes and such)
- [ ] Add proper unit tests
- [ ] Test latency with few complex hitboxes instead of many simple hitboxes

## BACKBURNER
- [ ] Allow general getting of intersection location
- [ ] add between-timestep intersection finding - requires generalized intersection finding
- [ ] Add onCollision type event listener
- [ ] put stuff on npm (and make into a proper multi-file module)
- [ ] Allow naming of parts of a hitbox and getting of which part exactly intersects
- [ ] Handle strokeWeight (can make some use if isPointInStroke)
- [ ] Handle strokeWeightMode in _draw for debug-mode drawing
- [ ] Handle strokeCap and strokeJoin
- [ ] Intersection of two bezier curves
- [ ] Make self-intersecting polygon detection more efficient by using https://en.wikipedia.org/wiki/Bentley%E2%80%93Ottmann_algorithm and https://github.com/luciopaiva/heapify

## SUBTRACTION
- Requires generalized intersection finding that supports infinite-point intersections.
- The general intersection of the shapes I support is a set of path-shapes (shape with an outline consisting of lines and arcs).
- Hitboxes now have layers of components, alternating between an ADD layer and a SUB layer.
- To check if a hitbox collides with another, do the following:
	1. Get the topmost ADD layer, and the SUB layer above it (or empty layer if there is none)
	2. Get intersection of the other hitbox with the ADD layer (if they don't collide, skip to next layer pair)
	3. Check if intersection is entirely within the SUB layer (easy to check with path shapes - make sure a representative point is inside AND the outlines never intersect)
	4. If intersection not entirely within SUB, return true. If it is, then we try again with the next layer pair (until none are left and we return false).
- Will need to fix debug drawing to work with subtraction (draw everything onto an image without opacity, then draw the whole image with opacity)

## DONE
- [x] Large-scale latency tests
- [x] Detect and reject self-intersecting polygons (some can be decomposed into normal ones, but some require subtraction - https://web.archive.org/web/20100805164131/http://www.cis.southalabama.edu/~hain/general/Theses/Subramaniam_thesis.pdf)
- [x] Add support for WEBGL mode
